# Generated by Django 2.2 on 2020-07-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accrancher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SvaeChkbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(max_length=50)),
                ('names', models.TextField()),
            ],
        ),
    ]
